### ISSUE TITLE
Deployen auf unseren Server

### ISSUE THREAD

**Issue by milafrerichs** [codeformuenster/WhatsMyDistrict#1]
Die Readme durchgehen und das ganze auf unseren Server aufsetzen.

**Comment by djmaze** [comment]
Erledigt. Läuft jetzt, solange wir noch keine passende Subdomain o.ä. haben, unter http://forum.codeformuenster.org:5005/

**Comment by milafrerichs** [comment]
cool. awesome. ihr seid also fleißig am hacken? @djmaze soll ich eine subdomain einrichten?
habt ihr euch was überlegt?
grüße an die crowd in ms aus Portland.

**Comment by djmaze** [comment]
Ja, unsere kleine Truppe ist hier am werkeln. 

Ich habe gesehen, dass WhatsMyDistrict ja letztlich nur eine sehr einfach Anzeige-App ist. Die Daten muss man in einem bestimmten Format als Datenbank-Dump in Postgres einspielen. Das dürfte also die meiste Arbeit sein.

Solange da aber noch keine echten Daten drin sind und somit nur die Daten aus diesem Beispielort sichtbar sind, macht es wohl noch keinen Sinn, das öffentlich auszuliefern.

Vom Namen her müssten wir uns wohl auch was Deutsches überlegen. Habe da jetzt gerade keine direkte Idee. 

Viele Grüße (auch von den anderen ) in die Staaten!
